version: '3.6'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 18941:5432

  bt_api:
    image: bt_api
    build: .
    depends_on:
      - db
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=critical
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8080
      - DATABASE_URL=postgres://username:password@db:5432/postgres
      - JWT_SECRET=3nEU6FVYvVi
    ports:
      - "8080:8080"